name: Create Staging Release
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: develop
        DEFAULT_BUMP: patch
        DRY_RUN: true
    - name: Echo the calculated tag
      run: |
        echo ${{ steps.tag_version.outputs.tag }}
        echo ${{ steps.tag_version.outputs.new_tag }}
        echo ${{ steps.tag_version.outputs.part }}
    - name: Echo if major Bump
      if: ${{ steps.tag_version.outputs.part == 'major' }}
      run: |
        echo "It's a MAJOR! We should release to PRODUCTION"
    - name: Echo if minor or patch
      if: ${{ steps.tag_version.outputs.part != 'major' }} 
      run: |
        echo "It's a MINOR or PATCH! We should release to STAGING"